### PR TITLE
Update documentation and tests

### PR DESCRIPTION
**Pull request by radiovisual**
also adds in general linting for better readability and updated travis.

### CODE REVIEW

**Comment by radiovisual** [comment]
You will notice that I switched the Implementation to Edd Mann's first implementation, because the performance is the same as Implementation Number 6, without violating any best practices.

**Comment by radiovisual** [comment]
I know it is a massive Pull Request (sorry!), but I wanted you to see each change one-by-one. Feel free to squash them all into a single commit, if you want. 

If you want to see how the changes will appear on your repo, then you can just [review my fork](https://github.com/radiovisual/reverse-string) to see everything at once.

**Comment by cedced19** [comment]
You are awesome. I created this repositories to joke two years ago. By reading your commits I have seen a lot of mistakes I did,  maybe because I come back from plane 😁.  More seriously I will publish to npm tomorrow. Thank you ! 😊

**Comment by radiovisual** [comment]
No problem! Even the "joke" modules can turn out to be useful. For Front-end (UI) work, it can be helpful to have a reliable way to reverse a string.

**Pull request merged**
